services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./vectorstore:/app/vectorstore
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-tinyllama}
    env_file:
      - .env
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped

  ollama:
    image: ollama/ollama:0.10.1
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "ollama list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "ollama serve &
       pid=$$!
       sleep 10
       ollama pull ${OLLAMA_MODEL:-tinyllama}
       wait $$pid"

volumes:
  ollama_models:
